apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: jenkins
  name: jenkins
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jenkins
    spec:
      containers:
      - image: jenkins/jenkins:lts
        name: jenkins
        resources: {}
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: claim
          subPath: jenkins/home
      volumes:
      - name: claim
        persistentVolumeClaim:
          claimName: smb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: media
spec:
  selector:
    app: jenkins
  ports:
    - name: sv1
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: sv2
      protocol: TCP
      port: 50000
      targetPort: 50000
  type: LoadBalancer
